import {
  FileText,
  Image,
  Video,
  Archive,
  Music,
  File,
  Mail,
  UploadCloud,
  Globe,
  FileType,
  Trash2,
  Star,
} from "lucide-react";

export const fileTypes = {
  "text/html": "web",
  "text/plain": "document",
  "text/css": "web",
  "text/javascript": "web",
  "application/javascript": "web",
  "text/xml": "document",
  "application/xml": "document",
  "image/jpeg": "image",
  "image/png": "image",
  "image/gif": "image",
  "image/svg+xml": "image",
  "image/bmp": "image",
  "image/x-icon": "image",
  "image/webp": "image",
  "application/json": "document",
  "application/pdf": "document",
  "application/zip": "archive",
  "application/gzip": "archive",
  "application/vnd.rar": "archive",
  "application/x-tar": "archive",
  "application/msword": "document",
  "application/vnd.ms-excel": "document",
  "application/vnd.ms-powerpoint": "document",
  "application/vnd.oasis.opendocument.text": "document",
  "application/vnd.oasis.opendocument.spreadsheet": "document",
  "audio/mpeg": "audio",
  "audio/wav": "audio",
  "audio/ogg": "audio",
  "audio/midi": "audio",
  "audio/x-midi": "audio",
  "video/mp4": "video",
  "video/webm": "video",
  "video/ogg": "video",
  "video/mpeg": "video",
  "video/x-msvideo": "video",
  "video/quicktime": "video",
  "font/woff": "font",
  "font/woff2": "font",
  "font/ttf": "font",
  "font/otf": "font",
  "multipart/form-data": "form",
  "multipart/mixed": "email",
  "application/octet-stream": "binary",
  "text/csv": "document",
} as any;

export const fileTypeIcons = {
  document: <FileText />,
  image: <Image />,
  video: <Video />,
  audio: <Music />,
  archive: <Archive />,
  font: <FileType />,
  form: <File />,
  email: <Mail />,
  binary: <UploadCloud />,
  web: <Globe />,
} as any;

export const sidebar_links = [
  {
    label: "All Files",
    Icon: File,
    href: "/all",
  },
  {
    label: "Favorites",
    Icon: Star,
    href: "/favorites",
  },
  // {
  //   label: "Trash",
  //   Icon: Trash2,
  //   href: "/trash",
  // },
];
