export const fileTypes = {
  "text/html": "html",
  "text/plain": "plain text",
  "text/css": "css",
  "text/javascript": "javascript",
  "application/javascript": "javascript",
  "text/xml": "xml",
  "application/xml": "xml",
  "image/jpeg": "jpeg",
  "image/png": "png",
  "image/gif": "gif",
  "image/svg+xml": "svg",
  "image/bmp": "bmp",
  "image/x-icon": "ico",
  "image/webp": "webp",
  "application/json": "json",
  "application/pdf": "pdf",
  "application/zip": "zip",
  "application/gzip": "gzip",
  "application/vnd.rar": "rar",
  "application/x-tar": "tar",
  "application/msword": "ms word",
  "application/vnd.ms-excel": "ms excel",
  "application/vnd.ms-powerpoint": "ms powerpoint",
  "application/vnd.oasis.opendocument.text": "odt",
  "application/vnd.oasis.opendocument.spreadsheet": "ods",
  "audio/mpeg": "mp3",
  "audio/wav": "wav",
  "audio/ogg": "ogg",
  "audio/midi": "midi",
  "audio/x-midi": "midi",
  "video/mp4": "mp4",
  "video/webm": "webm",
  "video/ogg": "ogg video",
  "video/mpeg": "mpeg",
  "video/x-msvideo": "avi",
  "video/quicktime": "quicktime",
  "font/woff": "woff",
  "font/woff2": "woff2",
  "font/ttf": "ttf",
  "font/otf": "otf",
  "multipart/form-data": "form data",
  "multipart/mixed": "email",
  "application/octet-stream": "binary data",
  "text/csv": "csv",
} as any;
